name: converter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  # http: ^1.2.2
  pdf: ^3.10.4
  printing: ^5.11.0
  image: ^4.1.3
  open_file: ^3.2.1
  intl: ^0.20.2
  shared_preferences: ^2.3.0
  file_picker: ^10.1.9
  media_scanner: ^2.2.0
  image_editor: ^1.4.0
  image_cropper: ^8.0.2
  http: ^1.2.0
  syncfusion_flutter_pdf: ^29.2.5
  cupertino_icons: ^1.0.8
  unity_ads_plugin: ^0.3.25


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # 👈 Added for app icon generation

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo1.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"  # 👈 Your custom app icon here
